version: '3.9'

services:

  chat-service-database:
    image: postgres
    container_name: chat-service-database
    restart: always
    environment:
      POSTGRES_DB: 'chat-service'
      POSTGRES_USER: ${CHAT_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHAT_SERVICE_DB_PASSWORD}
    ports:
      - "5001:5432"

  chat-service:
    container_name: chat-service
    image: chat-service:0.1.4
    restart: always
    build:
      context: ./services/chat-service/
      dockerfile: Dockerfile
    environment:
      CHAT_SERVICE_DB_URL: ${CHAT_SERVICE_DB_URL}
      CHAT_SERVICE_DB_USERNAME: ${CHAT_SERVICE_DB_USERNAME}
      CHAT_SERVICE_DB_PASSWORD: ${CHAT_SERVICE_DB_PASSWORD}
    depends_on:
      - chat-service-database
    ports:
      - "5000:8080"

      

  billing-service-database:
    image: postgres
    container_name: billing-service-database
    restart: always
    environment:
      POSTGRES_DB: 'billing-service'
      POSTGRES_USER: ${BILLING_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${BILLING_SERVICE_DB_PASSWORD}
    ports:
      - "5101:5432"

  billing-service:
    container_name: billing-service
    image: billing-service:0.1.0
    restart: always
    build:
      context: ./services/billing-service/
      dockerfile: Dockerfile
    environment:
      BILLING_SERVICE_DB_URL: ${BILLING_SERVICE_DB_URL}
      BILLING_SERVICE_DB_USERNAME: ${BILLING_SERVICE_DB_USERNAME}
      BILLING_SERVICE_DB_PASSWORD: ${BILLING_SERVICE_DB_PASSWORD}
    depends_on:
      - billing-service-database
    ports:
      - "5100:8080"
