version: '3.9'

services:

  chat-service-database:
    image: postgres
    container_name: chat-service-database
    restart: always
    environment:
      POSTGRES_DB: 'chat-service'
      POSTGRES_USER: ${CHAT_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHAT_SERVICE_DB_PASSWORD}
    ports:
      - "5001:5432"

  chat-service:
    image: chat-service:0.1.9
    restart: always
    build:
      context: ./services/chat-service/
      dockerfile: Dockerfile
    environment:
      CHAT_SERVICE_DB_URL: ${CHAT_SERVICE_DB_URL}
      CHAT_SERVICE_DB_USERNAME: ${CHAT_SERVICE_DB_USERNAME}
      CHAT_SERVICE_DB_PASSWORD: ${CHAT_SERVICE_DB_PASSWORD}
      BILLING_SERVICE_API_URL: ${BILLING_SERVICE_API_URL}
    depends_on:
      - chat-service-database
    ports:
      - 8080

  billing-service-database:
    image: postgres
    container_name: billing-service-database
    restart: always
    environment:
      POSTGRES_DB: 'billing-service'
      POSTGRES_USER: ${BILLING_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${BILLING_SERVICE_DB_PASSWORD}
    ports:
      - "5101:5432"

  billing-service:
    image: billing-service:0.1.5
    restart: always
    build:
      context: ./services/billing-service/
      dockerfile: Dockerfile
    environment:
      BILLING_SERVICE_DB_URL: ${BILLING_SERVICE_DB_URL}
      BILLING_SERVICE_DB_USERNAME: ${BILLING_SERVICE_DB_USERNAME}
      BILLING_SERVICE_DB_PASSWORD: ${BILLING_SERVICE_DB_PASSWORD}
      CHAT_SERVICE_API_URL: ${CHAT_SERVICE_API_URL}
    depends_on:
      - billing-service-database
    ports:
      - 8080

  payment-service-database:
    image: postgres
    container_name: payment-service-database
    restart: always
    environment:
      POSTGRES_DB: 'payment-service'
      POSTGRES_USER: ${PAYMENT_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${PAYMENT_SERVICE_DB_PASSWORD}
    ports:
      - "5201:5432"

  payment-service:
    image: payment-service:0.1.2
    restart: always
    build:
      context: ./services/payment-service/
      dockerfile: Dockerfile
    environment:
      PAYMENT_SERVICE_DB_URL: ${PAYMENT_SERVICE_DB_URL}
      PAYMENT_SERVICE_DB_USERNAME: ${PAYMENT_SERVICE_DB_USERNAME}
      PAYMENT_SERVICE_DB_PASSWORD: ${PAYMENT_SERVICE_DB_PASSWORD}
      BILLING_SERVICE_API_URL: ${BILLING_SERVICE_API_URL}
    depends_on:
      - payment-service-database
    ports:
      - 8080

  rsikspr-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:5000"
    restart: always
    depends_on:
      - chat-service
      - billing-service
      - payment-service
