version: '3.9'

services:

  rsikspr-service:
    image: rsikspr
    container_name: rsikspr-service
    depends_on:
      - rsikspr-db
    ports:
      - "5555:8080"

  rsikspr-db:
    image: postgres
    container_name: rsikspr-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5550:5432"
